# This configuration is used when running the GraalVM instance natively (on a server) or within Docker

fluidity:
  prefix: fluidity-dev
  services:
    storage: SERVER
    indexer: SERVER
    query: SERVER

quarkus:
  log:
    level: TRACE
