# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
orbs:
  vm-install-tools: entur/vm-install-tools@0.0.4
jobs:
  build:
    # Use "machine" instead of e.g. "docker" for better/faster results
    machine:
      image: ubuntu-1604:201903-01

    # Uses a "medium" sized machine - maybe increase this to "large" if you pay for CircleCI
    resource_class: medium
    environment:
      MAVEN_OPTS: -Xmx6400m
      # Set the GRAALVM_HOME env variable to the location where we will be installing GraalVM
      GRAALVM_HOME: /home/circleci/repo/.graalvm

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - store_test_results:
          path: test-results

      #      - run:
      #          name: install java-11
      #          command: >
      #            sudo apt-get
      #            sudo sh -c 'for bin in /usr/lib/jvm/jdk-11.0.3+7/bin/*; do
      #            update-alternatives --install /usr/bin/$(basename $bin) $(basename $bin)
      #            $bin 100; done'
      #
      #            sudo sh -c 'for bin in /usr/lib/jvm/jdk-11.0.3+7/bin/*; do
      #            update-alternatives --set $(basename $bin) $bin; done'

      - run:
          name: install java-o11
          command: |
            sudo apt-get update
            sudo apt-get install openjdk-11-jdk
            sudo update-java-alternatives -s java-11-openjdk-amd64
            export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/
            export PATH=$JAVA_HOME/bin:$PATH
            java -version
            mvn -N io.takari:maven:wrapper -Dmaven=3.6.3

      - run:
          name: Install module deps download to work
          command: ./mvnw package install -Dmaven.test.skip=true

      # Download maven dependencies so that we can cache them
      # ########################
      - run:
          name: Download Dependencies
          command: ./mvnw dependency:go-offline



      # Standard maven build and test phases - does not perform a native build (or verify)
      # ########################
      - run:
          name: Build (Standard)
          command: ./mvnw clean package -DskipTests -Dmaven.test.skip=true
      - run:
          name: Unit Test
          command: ./mvnw -Daws.region=eu-west-2 test
      - run:
          name: Integration Test
          command: ./mvnw -Daws.region=eu-west-2 test -P integration

#      - run: mvn package install -Dmaven.test.skip=true
      #- run: mvn integration-test
