# DEV Configuration file
# key = value

# used to configured how real the test is;
# TEST = no connectivity; DEV = connected; PROD = connected
#
cloud:
  region: eu-west-2

fluidity:
  prefix: fluidity-dev
  services:
    storage: TEST
    indexer: TEST
    query: TEST

"%dev":
  fluidity:
    services:
      storage: AWS
      indexer: AWS
      query: AWS
  quarkus:
    dynamodb:
      aws:
        region: eu-west-2
        credentials:
          type: default


"%prod":
  quarkus:
    dynamodb:
      aws:
        region: eu-west-2
        credentials:
          type: default
  fluidity:
    prefix: fluidity-prod
    services:
      storage: AWS
      indexer: AWS
      query: AWS


quarkus:
    dynamodb:
      aws:
        credentials:
          type: default
    log:
      level: INFO
      console:
        enable: true
        format: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%c] %s%e%n"
        level: INFO

      file:
        enable: true
        path: ./logs/fluidity.log
        level: INFO
        format: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%c{3.}]] (%t) %s%e%n"

      # App loggers
      category:
        "io.fluidity":
          level: INFO